"""Writes COVERAGE.md: every game id from the voxel dump (ref_index.json) and the FurnitureLibrary sources -> HD asset
(.blend, preview tile, tris, size deviation) or the reason it has none. Plain python3 (no Blender).

python3 coverage.py"""
import glob
import json
import os
import re

HERE = os.path.dirname(os.path.abspath(__file__))
HD = os.path.dirname(HERE)
REPO = os.path.abspath(os.path.join(HD, "..", "..", ".."))

# ids without their own asset, and why
SKIPPED = {
    "tree_planted": "no voxel grid: drawn by CropVisuals (growth stages of the crop / tree models), not a FurnitureLibrary mesh",
    "WorldKit": "item model (Items/WorldItemModels, dropped kit crate): items are outside this pass",
    "CampfireLogs": "per-count log piles of World/Campfire: one HD log (CampfireLog) is instanced per log",
}
MAPPED = {   # dumped mesh -> the asset that carries it
    "Furniture_pipe": ("pipe", "same mesh as the pipe spool"),
    "Furniture_cable": ("cable", "same mesh as the cable spool"),
    "Furniture_stamp": ("stamp_mill", "stamps are the movers Stamp0..2 of stamp_mill"),
    "floodlight_mast_bulb": ("floodlight_mast", "Bulb part of the lamp asset"),
    "light_pendant_bulb": ("light_pendant", "Bulb part of the lamp asset"),
    "light_strip_bulb": ("light_strip", "Bulb part of the lamp asset"),
    "light_wall_bulb": ("light_wall", "Bulb part of the lamp asset"),
    "streetlamp_cobra_bulb": ("streetlamp_cobra", "Bulb part of the lamp asset"),
    "streetlamp_gas_bulb": ("streetlamp_gas", "Bulb part of the lamp asset"),
    "streetlamp_pole_bulb": ("streetlamp_pole", "Bulb part of the lamp asset"),
    "streetlamp_solar_bulb": ("streetlamp_solar", "Bulb part of the lamp asset"),
}
NOTES_SITES = ("Site templates (`site:{cell}:{piece}`) are generated per site by SiteBuilder, so they are covered by the "
               "modular kits `Site_Bunker_*`, `Site_Tunnel_*`, `Site_Airfield_*` (sites.py) that the generators can place "
               "cell by cell instead of one asset per template.")


def load():
    ref = json.load(open(os.path.join(HERE, "ref_index.json")))
    cov = {}
    for f in sorted(glob.glob(os.path.join(HD, "*", "coverage_*.json"))):
        for k, v in json.load(open(f)).items():
            v["script"] = os.path.relpath(f, HD).replace("coverage_", "").replace(".json", ".py")
            cov[k] = v
    furn = set()
    for f in glob.glob(os.path.join(REPO, "Assets/MadMax/Runtime/Building/FurnitureLibrary*.cs")):
        s = open(f).read()
        furn |= set(re.findall(r'\bid = "([a-z_0-9]+)"', s)) | set(re.findall(r'\bD\("([a-z_0-9]+)"', s))
    return ref, cov, furn


def row(gid, c):
    dev = "" if c.get("dim_dev") is None else "%.3f" % c["dim_dev"]
    flags = []
    if not c.get("budget_ok", True):
        flags.append("over/under budget")
    if c.get("dim_dev") is not None and c["dim_dev"] > 0.035:
        flags.append("size dev")
    note = c.get("note", "") or ""
    if flags:
        note = (note + "; " if note else "") + ", ".join(flags)
    dims = " x ".join("%.2f" % x for x in c["dims"])
    return "| `%s` | %s | `%s` | %s | %d | %s | %s | %s |" % (gid, c["category"], c["blend"], c["tile"], c["tris"], dims, dev, note.replace("|", "/"))


def main():
    ref, cov, furn = load()
    groups = {}
    for gid, c in cov.items():
        groups.setdefault(c["group"], []).append(gid)
    out = ["# HD asset coverage", "",
           "Generated by `tools/blender/hd/world/coverage.py` from the `coverage_*.json` files the build scripts write and the "
           "voxel dump `world/ref_index.json` (every mesh the game bakes or builds at runtime). Sizes are game metres "
           "(x, y, z); *dev* = largest axis difference to the voxel template in metres (movers excluded). Preview tiles: "
           "`hd_preview/<group>/<tile>.png` (+ `_px.png` pixel view).", ""]
    total = 0
    for grp in ("furniture", "world", "animals"):
        ids = sorted(groups.get(grp, []), key=str.lower)
        total += len(ids)
        out += ["## %s (%d assets)" % (grp.capitalize(), len(ids)), "",
                "| id | category | blend | tile | tris | size m | dev | note |", "|---|---|---|---|---|---|---|---|"]
        out += [row(g, cov[g]) for g in ids]
        out.append("")
    # gaps
    covered = set(cov)
    animal_ids = {k[7:] for k in ref if k.startswith("animal:")}
    gaps, mapped, skipped = [], [], []
    for gid in sorted(set(ref) | furn, key=str.lower):
        if gid in covered:
            continue
        if gid.startswith("animal:") and gid[7:] in covered:
            continue
        if gid in MAPPED:
            mapped.append("| `%s` | `%s` | %s |" % (gid, MAPPED[gid][0], MAPPED[gid][1]))
        elif gid in SKIPPED:
            skipped.append("| `%s` | %s |" % (gid, SKIPPED[gid]))
        else:
            gaps.append(gid)
    for gid in SKIPPED:
        if gid not in ref and gid not in furn:
            skipped.append("| `%s` | %s |" % (gid, SKIPPED[gid]))
    out += ["## Carried by another asset", "", "| game mesh | asset | how |", "|---|---|---|"] + mapped + [""]
    out += ["## Skipped", "", "| id | why |", "|---|---|"] + sorted(skipped) + ["", NOTES_SITES, ""]
    out += ["## Gaps", ""] + (["- `%s`" % g for g in gaps] if gaps else ["None: every dumped mesh and every FurnitureLibrary id is covered, mapped or skipped with a reason."]) + [""]
    missing_animals = sorted(a for a in animal_ids if a not in covered)
    out += ["Animals: %d / %d AnimalLibrary species%s, plus extras (PackMule, Bat, SeaFish0-3, Jellyfish)." % (
        len(animal_ids) - len(missing_animals), len(animal_ids), "" if not missing_animals else " (missing: %s)" % ", ".join(missing_animals)), ""]
    flagged = sorted(g for g, c in cov.items() if not c.get("budget_ok", True))
    big = sorted(g for g, c in cov.items() if c.get("dim_dev") is not None and c["dim_dev"] > 0.1)
    out += ["Total HD assets: %d. Outside the triangle budget: %s. Size deviation > 0.1 m: %s." % (
        total, ", ".join(flagged) or "none", ", ".join(big) or "none"), ""]
    out += ["## Export notes (PIPELINE.md)", "",
            "- Axes: game (x, y, z) -> Blender (-x, -z, y), the same mapping as `cars/` and `character/` (no `mirroredOnExport`).",
            "- Roots are empties named like the game id at the asset origin; the .blend files keep the preview layout offsets "
            "(the exporter resets roots to the origin). World buildings carry the 180 degree preview turn only in the renders.",
            "- Vegetation has a `Sway` point attribute, 0 at the root -> 1 at the tips; the exporter's `Col.a` is the voxel "
            "convention (1 = rooted), so write `Col.a = 1 - Sway`.",
            "- Buildings: `Shell_<Material>` (carvable, root prop `shell_parts`), `Detail`, `Glass`; movers (rotors, leaves, "
            "stamps, heads) are separate objects with `mover = True` and their pivot at the joint.",
            "- Animals: root empty / `Rig` armature (one bone per part) / part meshes bone-parented; object props `part` "
            "(name as in Animal's Rig), `rig_part`, `index`, `pivot_game_m`; root props `ref_height`, `species_name`.",
            "- Emissive lamp materials are named `Lamp*` (white / amber / red) so the exporter's lamp classes pick them up.", ""]
    open(os.path.join(HERE, "COVERAGE.md"), "w").write("\n".join(out))
    print("assets", total, "gaps", gaps, "mapped", len(mapped), "skipped", len(skipped))


if __name__ == "__main__":
    main()
